# Generated by Django 3.1 on 2020-10-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysic_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='title_tag',
            field=models.CharField(default='Casmena', max_length=255),
        ),
    ]
