# Generated by Django 3.1 on 2020-10-13 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mysic_blog', '0006_auto_20201013_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(default='tba', max_length=255),
        ),
    ]
